name: "S3 Sync & Invalidate Distribution"
description: "Sync a directory to an AWS S3 repository and invalidate a Cloudfront distribution"
author: Digital Scarcity
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
